services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:963"
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache

      - type: bind
        source: /nvme
        target: /nvme
        read_only: true

      - type: bind
        source: ./media
        target: /media
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
