services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps/homarr/configs/:/app/data/configs
      - ./apps/homarr/icons/:/app/public/icons
      - ./apps/homarr/data/:/data

      - ./apps/homarr/favicon/:/app/public/imgs/favicon

    ports:
      - '7575:7575'
    networks:
      local_network:
        ipv4_address: 192.168.2.2

################
### Jellyfin ###
################

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:963"
    volumes:
      - ./apps/jellyfin/config:/config
      - ./apps/jellyfin/cache:/cache

      - type: bind
        source: /nvme
        target: /nvme

      - type: bind
        source: ./shared/media
        target: /media
        read_only: true

    restart: 'unless-stopped'
    ports:
      - '8096:8096'
    networks:
      local_network:
        ipv4_address: 192.168.2.3

#################
### Jellyseer ###
#################

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    ports:
      - 5055:5055
    volumes:
      - ./apps/jellyseer:/app/config

      - type: bind
        source: /nvme
        target: /nvme

      - type: bind
        source: ./shared/media
        target: /media
        read_only: true

    restart: unless-stopped
    networks:
      local_network:
        ipv4_address: 192.168.2.4

###############
### Powlarr ###
###############

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./apps/prowlarr/config/:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      local_network:
        ipv4_address: 192.168.2.5

# ##############
# ### Sonarr ###
# ##############

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /nvme:/nvme
      - ./apps/sonarr/config:/config
      - ./apps/sonarr/data:/data
      - ./shared:/data

    ports:
      - 8989:8989
    restart: unless-stopped

    networks:
      local_network:
        ipv4_address: 192.168.2.6

##############
### Radarr ###
##############

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /nvme:/nvme
      - ./apps/radarr/config:/config
      - ./apps/radarr/data:/data
      - ./shared:/data

    ports:
      - 7878:7878
    restart: unless-stopped

    networks:
      local_network:
        ipv4_address: 192.168.2.7


####################
### Transmission ###
####################

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: TransmissionVPN
    restart: on-failure:2
    cap_add:
        - NET_ADMIN
    volumes:
        - ./apps/transmission/config/protonvpn:/etc/openvpn/custom/
        - ./apps/transmission/config/transmission:/config
        - ./shared/completed/:/data/completed
    environment:
        - OPENVPN_PROVIDER=custom
        - OPENVPN_CONFIG=mx.protonvpn.udp
        - OPENVPN_USERNAME=(your credentials here)
        - OPENVPN_PASSWORD=(your credentials here)
        - LOCAL_NETWORK=192.168.0.0/16
    logging:
        driver: json-file
        options:
            max-size: 10m
    ports:
        - 9091:9091

    networks:
      local_network:
        ipv4_address: 192.168.2.8

networks:
  local_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
